local _, Addon = ...

Addon.BINDING_PRESET_NAME = "Forever Controller"
Addon.BundledBindings = {
    PADLTRIGGER = { [""]="", ["SHIFT-"]="", ["CTRL-"]="", ["CTRL-SHIFT-"]="" },
    PADRTRIGGER = { [""]="", ["SHIFT-"]="", ["CTRL-"]="", ["CTRL-SHIFT-"]="" },
    PADLSHOULDER = { [""]="TARGETNEARESTFRIEND", ["SHIFT-"]="TARGETNEARESTFRIEND", ["CTRL-"]="TARGETNEARESTFRIEND", ["CTRL-SHIFT-"]="TARGETNEARESTFRIEND" },
    PADRSHOULDER = { [""]="TARGETSCANENEMY", ["SHIFT-"]="TARGETSCANENEMY", ["CTRL-"]="TARGETSCANENEMY", ["CTRL-SHIFT-"]="TARGETSCANENEMY" },
    PAD1 = { [""]="JUMP", ["SHIFT-"]="ACTIONBUTTON1", ["CTRL-"]="MULTIACTIONBAR1BUTTON1", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON1" },
    PAD2 = { [""]="", ["SHIFT-"]="ACTIONBUTTON2", ["CTRL-"]="MULTIACTIONBAR1BUTTON2", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON2" },
    PAD3 = { [""]="INTERACTTARGET", ["SHIFT-"]="ACTIONBUTTON3", ["CTRL-"]="MULTIACTIONBAR1BUTTON3", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON3" },
    PAD4 = { [""]="TURNORACTION", ["SHIFT-"]="ACTIONBUTTON4", ["CTRL-"]="MULTIACTIONBAR1BUTTON4", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON4" },
    PADDLEFT = { [""]="ACTIONBUTTON9", ["SHIFT-"]="ACTIONBUTTON5", ["CTRL-"]="MULTIACTIONBAR1BUTTON5", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON5" },
    PADDUP = { [""]="ACTIONBUTTON10", ["SHIFT-"]="ACTIONBUTTON6", ["CTRL-"]="MULTIACTIONBAR1BUTTON6", ["CTRL-SHIFT-"]="CLICK LM_B1:LeftButton" },
    PADDRIGHT = { [""]="ACTIONBUTTON11", ["SHIFT-"]="ACTIONBUTTON7", ["CTRL-"]="MULTIACTIONBAR1BUTTON7", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON7" },
    PADDDOWN = { [""]="ACTIONBUTTON12", ["SHIFT-"]="ACTIONBUTTON8", ["CTRL-"]="MULTIACTIONBAR1BUTTON8", ["CTRL-SHIFT-"]="MULTIACTIONBAR2BUTTON8" },
    PADBACK = { [""]="TOGGLEWORLDMAP", ["SHIFT-"]="TOGGLEWORLDMAP", ["CTRL-"]="TOGGLEWORLDMAP", ["CTRL-SHIFT-"]="TOGGLEWORLDMAP" },
    PADFORWARD = { [""]="CLICK ConsolePortMenuTrigger:LeftButton", ["SHIFT-"]="CLICK ConsolePortMenuTrigger:LeftButton", ["CTRL-"]="CLICK ConsolePortMenuTrigger:LeftButton", ["CTRL-SHIFT-"]="CLICK ConsolePortMenuTrigger:LeftButton" },
    PADSYSTEM = { [""]="TOGGLEWORLDMAP", ["SHIFT-"]="TOGGLEWORLDMAP", ["CTRL-"]="TOGGLEWORLDMAP", ["CTRL-SHIFT-"]="TOGGLEWORLDMAP" },
    PADSOCIAL = { [""]="TOGGLEWORLDMAP", ["SHIFT-"]="OPENALLBAGS", ["CTRL-"]="TOGGLECHARACTER0", ["CTRL-SHIFT-"]="TOGGLESPELLBOOK" },
    PADLSTICK = { [""]="TOGGLEAUTORUN", ["SHIFT-"]="", ["CTRL-"]="", ["CTRL-SHIFT-"]="" },
    PADRSTICK = { [""]="TOGGLEPINGLISTENER", ["SHIFT-"]="", ["CTRL-"]="", ["CTRL-SHIFT-"]="" },
}
